version: '3.7'

networks:
  proxy-network:
    driver: bridge
    external: true

services:
  db:
    stdin_open: true
    image: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    tty: true
    restart: on-failure
    networks:
      - proxy-network
    ports:
      - $POSTGRES_PORT:5432/tcp

  adminer:
    image: adminer
    restart: on-failure
    networks:
      - proxy-network
    ports:
      - 8080:8080